language: python
python: 
  - "3.6.10"
install: 
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script: 
  - python manage.py test
  - flake8 fullstack/views.py && flake8 fullstack/models.py 
  - flake8 fullstack/forms.py
  - flake8 fullstack/admin.py

