language: python
python: 
  - "3.6"
install: 
  - pip install -r requirements.txt
script: 
  - python smartcity/manage.py test
  - flake8 smartcity/fullstack/views.py && flake8 smartcity/fullstack/models.py 
  - flake8 smartcity/fullstack/forms.py
  - flake8 smartcity/fullstack/admin.py

